---
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: openshift-console-banner
spec:
  text: {{ .Values.banner.text }}-{{ .Values.banner.environment }}
  location: {{ .Values.banner.location }}
  color: {{ .Values.banner.color }}
  backgroundColor: {{ .Values.banner.background }}
