apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: flan-t5
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: flan-t5
  namespace: rhoai-demo-llm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: caikit
      name: ''
      resources: {}
      runtime: flan-t5
      storage:
        key: aws-connection-my-storage
        path: models/flan-t5-small-caikit
